### ISSUE TITLE
Create README.md

### ISSUE THREAD

**Issue by davidalami** [cinqmarsmedia/Copy-Editor-A-RegEx-Puzzle-Game#1]
Hello! Seems like a nice project, would like to test and contribute, however I failed to build and run the application.
The project needs README file with build and run instructions.

**Comment by ccj242** [comment]
Hey David, thanks so much for

**Comment by ccj242** [comment]
Hey David, thanks so much for your interest in the project! I had meant to upload a simple ReadMe and it slipped my mind, I have done so now and will embellish it further as I get more free time. Please let me know if you have any issues with my instructions or if I can help at all. Thanks!!

**Comment by davidalami** [comment]
Thank you, Christopher!
