### ISSUE TITLE
Might be a bug in Level 32 Consonent Consequences

### ISSUE THREAD

**Issue by MnFeN** [cinqmarsmedia/Copy-Editor-A-RegEx-Puzzle-Game#12]
The answer expects the string `"to throw,"` being replaced by `"to` instead of `"to,"` or something else. It could be easily fixed by adding a `(,")?` to the regex, but I doubt it is a bug which seems inconsistent with the instruction.  
  
![image](https://github.com/cinqmarsmedia/Copy-Editor-A-RegEx-Puzzle-Game/assets/85232361/c93606ca-02d1-43f8-9483-6818f7ddb20b)
  
Also, the two words `English` and `Belgrade` both have 3 consonant letters (`ngl` `lgr`), but the answer expect them to be unchanged:
  
![image](https://github.com/cinqmarsmedia/Copy-Editor-A-RegEx-Puzzle-Game/assets/85232361/29571053-5528-46a4-8051-83b360fdac95)

**Comment by MnFeN** [comment]
btw, a typo in level 39:
![image](https://github.com/cinqmarsmedia/Copy-Editor-A-RegEx-Puzzle-Game/assets/85232361/ce46a274-3a85-4f6b-a7b2-3a094de18616)

**Comment by ccj242** [comment]
Thanks so much @MnFeN! Will make these changes shortly.
