### ISSUE TITLE
Errors on application startup

### ISSUE THREAD

**Issue by davidalami** [cinqmarsmedia/Copy-Editor-A-RegEx-Puzzle-Game#2]
Hello, there is an error on starting the installed application via ```npm start```, possibly due to a missing file:

```
template error, "/home/zkiller/Copy-Editor-A-RegEx-Puzzle-Game/src/pages/home/selectflags.html": Error: 
ENOENT: no such file or directory, open 
'/home/zkiller/Copy-Editor-A-RegEx-Puzzle-Game/src/pages/home/selectflags.html' 
```
Also after, the development server starts, there are some other errors appearing in Chrome console, again probably due to missing files:
```
Failed to load resource: the server responded with a status of 404 (Not Found)
chart.js:1 Failed to load resource: the server responded with a status of 404 (Not Found)
:8101/home.html:1 Failed to load resource: the server responded with a status of 404 (Not Found)
polyfills.js:3 Unhandled Promise rejection: Failed to load home.html ; Zone: <root> ; Task: Promise.then ; Value: Failed to load home.html undefined
n.onUnhandledError @ polyfills.js:3
:8101/usrLvls.html:1 Failed to load resource: the server responded with a status of 404 (Not Found)
:8101/submitLvl.html:1 Failed to load resource: the server responded with a status of 404 (Not Found)
:8101/selectflags.html:1 Failed to load resource: the server responded with a status of 404 (Not Found)
```

**Comment by ccj242** [comment]
Hey @davidalami, I'm pretty sure I solved the issue in the latest commit. There was a typo when loading the component "selfectflags" vs "selectFlags" and while Mac and Windows are not case-sensitive, Linux appears to be. When I ran it on windows I also needed another command which I've added to the readme. If you can give the latest commit a try and see if it works for you, I'd deeply appreciate it. Thanks for your patience and sorry about that!

**Comment by davidalami** [comment]
Thank you @ccj242 , the issue is solved successfully! The application builds and runs on Linux.
