### ISSUE TITLE
Errors from npm install

### ISSUE THREAD

**Issue by DevilXD** [cinqmarsmedia/Copy-Editor-A-RegEx-Puzzle-Game#4]
I'm more of a Python guy, hence I've pretty much installed a fresh node-js.v13.14.0 (latest supported) on my Win7, as well as Visual Studio 2019 that it apparently needed, and I still can't get it to work. I tried following this too: https://stackoverflow.com/questions/39674390/error-with-npm-install-a-pre-gyp-error

But `npm install --global --production windows-build-tools` hangs on waiting for the log file from the installer.

I'd appreciate some directions on how to build this thing. Log file from `npm install` with the error is attached.

[2022-01-28T16_41_51_408Z-debug.log](https://github.com/cinqmarsmedia/Copy-Editor-A-RegEx-Puzzle-Game/files/7960364/2022-01-28T16_41_51_408Z-debug.log)

**Comment by ccj242** [comment]
Hey @DevilXD, sorry you're having issues. I tried a fresh clone on my windows machine (windows 10) with node 13.14 and I was able to reproduce your issue. The easiest fix would be to use an older version of node (I can confirm 10.15 works). it has to do with some of the firebase dependencies. You can install nvm to quickly install and switch between node versions. Meanwhile I'll look into a more elegant fix for newer versions of node. Thanks.

**Comment by DevilXD** [comment]
I got it to work with v10.15.3 of node, thank you =)

Not sure if you'd want to leave this issue up for tracking purposes or not, so I'm withholding from closing it myself. Feel free to close it you'd want to =)
